<a href="https://colab.research.google.com/github/sivaganesh7/Machine-learning-/blob/note-books/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Module Course


##start module


In [3]:
pip install numpy


In [4]:
import numpy as n

In [49]:
a=n.array([[1,2,3,4],[5,6,7,8]])
print(a)
print("size: ",a.size)
print("item size: ",a.itemsize)
print("shape: ",a.shape)
print("dimension: ",a.ndim)
a1=n.arange(1,7) #arange method
print(a1.reshape(2,3))#reshape method
print(a1)
b=n.ones((3,3),dtype=complex) #ones
print(b)
print("chanege dtype: ",b.astype(int))
print(b)
n.zeros((3,3),dtype=int) #zeros
c=n.eye((3),dtype=int) #identy
print(c)
d=n.identity((3),dtype=int)
print(d)
print(n.linspace(-10,10,10))
arr = n.array(['apple', 'banana', 'cherry'],dtype=bool)
print(arr)
print(arr.dtype)


[[1 2 3 4]
 [5 6 7 8]]
size:  8
item size:  8
shape:  (2, 4)
dimension:  2
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
chanege dtype:  [[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
[ True  True  True]
bool


<ipython-input-49-9efbdc04841c>:12: ComplexWarning: Casting complex values to real discards the imaginary part
  print("chanege dtype: ",b.astype(int))


##Data Types in NumPy


NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

1.**strings** - used to represent text data, the text is given under quote marks. e.g. "ABCD".

2.**integer** - used to represent integer numbers. e.g. -1, -2, -3    

3.**float** - used to represent real numbers. e.g. 1.2, 42.42.

4.**boolean** - used to represent True or False.

5.**complex** - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void ) *italicized text*

In [50]:
a=n.array([[1,2,3,4],[5,6,7,8]])
print(a.dtype)

arr = n.array(['apple', 'banana', 'cherry'],dtype=bool)
print(arr)
print(arr.dtype)

int64
[ True  True  True]
bool
