<a href="https://colab.research.google.com/github/sivaganesh7/Machine-learning-/blob/note-books/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Module Course


##start module


In [6]:
pip install numpy


In [7]:
import numpy as n

In [4]:
a=n.array([[1,2,3,4],[5,6,7,8]])
print(a)
print("size: ",a.size)
print("item size: ",a.itemsize)
print("shape: ",a.shape)
print("dimension: ",a.ndim)
a1=n.arange(1,7) #arange method
print(a1.reshape(2,3))#reshape method
print(a1)
b=n.ones((3,3),dtype=complex) #ones
print(b)
print("chanege dtype: ",b.astype(int))
print(b)
n.zeros((3,3),dtype=int) #zeros
c=n.eye((3),dtype=int) #identy
print(c)
d=n.identity((3),dtype=int)
print(d)
print(n.linspace(-10,10,10))
arr = n.array(['apple', 'banana', 'cherry'],dtype=bool)
print(arr)
print(arr.dtype)


[[1 2 3 4]
 [5 6 7 8]]
size:  8
item size:  8
shape:  (2, 4)
dimension:  2
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
chanege dtype:  [[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
[ True  True  True]
bool


<ipython-input-4-1fc0031e27bb>:12: ComplexWarning: Casting complex values to real discards the imaginary part
  print("chanege dtype: ",b.astype(int))


##Data Types in NumPy


NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

1.**strings** - used to represent text data, the text is given under quote marks. e.g. "ABCD".

2.**integer** - used to represent integer numbers. e.g. -1, -2, -3    

3.**float** - used to represent real numbers. e.g. 1.2, 42.42.

4.**boolean** - used to represent True or False.

5.**complex** - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void ) *italicized text*

In [5]:
a=n.array([[1,2,3,4],[5,6,7,8]])
print(a.dtype)

arr = n.array(['apple', 'banana', 'cherry'],dtype=bool)
print(arr)
print(arr.dtype)

n.zeros((2,3),dtype=int) #zeros

int64
[ True  True  True]
bool


array([[0, 0, 0],
       [0, 0, 0]])

#Array Functions

In [ ]:
a=n.array([[1,2,3],[88,24,55]])
print(a)
print(a.shape)
print(n.max(a))
print("axis=1 means row wise: ",n.max(a,axis=1))
print("axis=0 means column wise: ",n.max(a,axis=0))
print(n.min(a))
print(n.sum(a))
print(n.prod(a))
print("array split: ",n.array_split(a,3,axis=1))
print("where: ",n.where(a==88))





[[ 1  2  3]
 [88 24 55]]
(2, 3)
88
axis=1 means row wise:  [ 3 88]
axis=0 means column wise:  [88 24 55]
1
173
696960
array split:  [array([[ 1],
       [88]]), array([[ 2],
       [24]]), array([[ 3],
       [55]])]
where:  (array([1]), array([0]))
0.16553615698481294


#**Slicing**


In [ ]:
a1=n.array([[1,2,3],[4,5,6]])
a2=n.array([[7,8],[9,10],[11,12]])
print("a1=",a1,end="\n")
# print("a2=",a2)

print("\n",a2[0:])

a1= [[1 2 3]
 [4 5 6]]


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

#Random Module


##-->Random Methods:

In [ ]:
x=n.random.random() #random
print(x)
x=n.random.randint(1,20) #randint
print(x)
x=n.random.randint(1,20,(3,3)) #random integers b/w 1 and 20 with array size 3x3
print(x)
print(n.random.rand())
#choice
x=n.random.choice([1,2,3,4,5,6,7,8,9,10],(2,2)) #choice is select elements from give array
print(x)
#permutations
arr = n.array([1, 2, 3, 4, 5])
shuffled = n.random.permutation(arr)
print("Shuffled array:", shuffled)

#dot product
a1=n.array([[1,2,3],[4,5,6]])
a2=n.array([[7,8],[9,10],[11,12]])
print(n.dot(a1,a2))

print(a2)


0.2962735057040824
13
[[ 1  7  9]
 [ 1 12  8]
 [11 19 17]]
0.71134195274865
[[ 3  1]
 [ 5 10]]
Shuffled array: [5 4 3 1 2]
[[ 58  64]
 [139 154]]
[[ 7  8]
 [ 9 10]
 [11 12]]


#Assignment

In [ ]:
a=n.arange(10,51,5)
print(a)

arr=n.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr[1:3,0:2])
arr[arr>4]=0
print(arr)

a= n.array([1, 2, 3])
b =n.array([4, 5, 6])
print(a)
print(b)
print("add=a,"+b)
print(a*b)



[10 15 20 25 30 35 40 45 50]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]
[1 2 3]
[4 5 6]


UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U6'), dtype('int64')) -> None

In [22]:
arr = n.array([1, 2, 3, 4])
a=arr+4
print(a*2)

arr = n.random.randint(1, 101, size=(3, 4, 5))
print(arr)
second_layer = arr[1, :, :]
print(second_layer)
# Reshape the boolean mask to match the dimensions of arr
mask = (arr % 3 == 0).reshape(arr.shape)
arr[mask] = 1  # Apply the mask to modify arr
print(arr)

[10 12 14 16]
[[[49 98 63 40 21]
  [77 86 27  5 51]
  [ 7 81 16 68 60]
  [31 59 53 10 29]]

 [[ 4 51 98 94 50]
  [36 12 39 53 62]
  [94 50 72 58 39]
  [99 30 31 70  1]]

 [[13 78 76 33 25]
  [70 77 33 56 42]
  [29 24 85 87 89]
  [87  9 50 42 74]]]
[[ 4 51 98 94 50]
 [36 12 39 53 62]
 [94 50 72 58 39]
 [99 30 31 70  1]]
[[[49 98  1 40  1]
  [77 86  1  5  1]
  [ 7  1 16 68  1]
  [31 59 53 10 29]]

 [[ 4  1 98 94 50]
  [ 1  1  1 53 62]
  [94 50  1 58  1]
  [ 1  1 31 70  1]]

 [[13  1 76  1 25]
  [70 77  1 56  1]
  [29  1 85  1 89]
  [ 1  1 50  1 74]]]
